// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lghuweolrrnzbrcablod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnaHV3ZW9scnJuemJyY2FibG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MTgzODMsImV4cCI6MjA1ODM5NDM4M30.VqGFvOyhaZi_c1iLoN22AMZtCKE3PhWQrVx_I8shqis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);